version: '3.8'

services:
  bday-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - PORT=8080
      - APP_TITLE=Birthday list
      - MONGO_URL=mongodb://mongo-db:27017/bday
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:6.0
    volumes:
      - dane-mongodb:/data/db

volumes:
  dane-mongodb: