apiVersion: apps/v1
kind: Deployment
metadata:
  name: bday-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bday-app
  template:
    metadata:
      labels:
        app: bday-app
    spec:
      containers:
        - name: bday-container
          image: emiliakochutek/bday-app:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bday-config
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: bday-secret
                  key: mongo-url